version: '3.8'
services:
  db:
    container_name: postgres_proposal-service
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRESS_DB=postgres


